version: '3'
services:
    nginx:
        image: nginx:1.12 #使用nginx官方镜像
        container_name: nginx #nginx容器名称
        working_dir: /application #容器里的工作目录，也可与自己的应用重名。
        volumes:
            - ./www:/application # 将本地代码挂载到容器的application目录里
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # nginx配置文件 #nginx配置文件挂载到容器的default.conf文件上，相当于前者内容写入后者。
        ports:
            - "8080:80" #将nginx容器的80端口映射到宿主机的8080端口上。看具体情况，如果宿主机80端口没有被占用可以映射到宿主机的80端口。也可以不指定，自动映射。但要访问时需要查明容器的80端口具体映射到了宿主机的哪个端口上。
        networks: #网络限制，于php在同一个网络里，只能访问php
            - frontend
        depends_on: #依赖于php
            - php
        restart: always
    php:
        image: "gaohongxinag/lnmp-php:php7.2" # 使用自己配置的镜像文件
       #注意：php镜像上传到了docker hub上，image直接去pull此镜像。等同于下面的build句（指定php dockerfile所在的目录）。用哪一个都可以
       # build: ./php
        container_name: php
        working_dir: /application
        volumes:
            - ./www:/application 
            - ./php/php.ini:/etc/php/conf.d/
        networks: #加入了两个网络组，既可以与nginx通信，又可以与mysql通信。
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD:1
        depends_on: # 依赖于mysql
            - mysql
        restart: always
    mysql:
        image: mysql:5.7
        container_name: mysql
        working_dir: /application
        volumes:
            - ./mysql/data:/var/lib/mysql #mysql数据在本机相对当前目录的mysql/data目录下，挂载在容器里/var/lib/mysql目录下
            - ./mysql/mysql.conf:/etc/mysql/mysql.conf.d/mysql.cnf #mysql目录下的mysql.conf文件挂载到容器的/etc/mysql/mysql.conf.d/mysql.cnf文件上。相当于吧mysql.conf文件里的内容写入容器的mysql.cnf文件里
        environment:
            - TZ='Asia/Shanghai'
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=1
            - MYSQL_PASSWORD=1
            - MYSQL_DATABASE=www_blockchant_cn 
        networks:
            - backend
        restart: always
#volumes:
#    mysql-data:

networks: # 自定义的网络组
    frontend:
    backend: